import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import Card from "../components/Card";
import Header from "../components/Header";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // const creator = api.example.

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headline="Get transcripts and stats about your favorite streamers"/>
      <section className="space-y-2">
        <h1 className="text-xl font-bold">All Streamers:</h1>
        <Card heading="HasanAbi" description="Political Streamer." to="creator/0"/>
      </section>
    </>
  );
};

export default Home;
